logging:
  json_format: false
  level: trace

api:
  enabled: true
  port: 8080

workers:
  enabled: true
  count: 1
  data_directory: ./data/worker

blob_store:
  type: memory

data_sink:
  type: memory

queue:
  type: memory

database:
  type: static

destinations:
  - type: redshift
    name: Local DuckDB file
    api_keys:
      - local 
    settings:
  
      redshift_host: ""
      redshift_port: 5439 
      redshift_user: ""
      redshift_password: ""
      redshift_database: ""
      redshift_schema: public

      s3_region: ""
      s3_access_key_id: ""
      s3_secret_access_key: ""
      s3_bucket: ""